import type { IdentityDimensionKey, IdentityQuestion } from "./types";

export const IDENTITY_DIMENSIONS: Record<
  IdentityDimensionKey,
  { label: string; shortLabel: string; description: string; color: string; soft: string }
> = {
  self_clarity: {
    label: "Self-Clarity",
    shortLabel: "Clarity",
    description: "How clearly you understand who you are, what you want, and how you work.",
    color: "#4f46e5",
    soft: "#eef2ff",
  },
  authenticity: {
    label: "Authenticity",
    shortLabel: "Authenticity",
    description: "How closely your outward behaviour matches your private sense of self.",
    color: "#0f766e",
    soft: "#ccfbf1",
  },
  values_alignment: {
    label: "Values Alignment",
    shortLabel: "Values",
    description: "How strongly your choices reflect what genuinely matters to you.",
    color: "#7c3aed",
    soft: "#ede9fe",
  },
  social_adaptation: {
    label: "Social Adaptation",
    shortLabel: "Adaptation",
    description: "How much your expression shifts across people, roles, and environments.",
    color: "#db2777",
    soft: "#fce7f3",
  },
  external_influence: {
    label: "External Influence",
    shortLabel: "Influence",
    description: "How much expectations, approval, comparison, or judgement shape your self-evaluation.",
    color: "#f97316",
    soft: "#ffedd5",
  },
  identity_stability: {
    label: "Identity Stability",
    shortLabel: "Stability",
    description: "How coherent your sense of self remains across time and context.",
    color: "#0284c7",
    soft: "#e0f2fe",
  },
};

const question = (
  id: number,
  code: string,
  text: string,
  dimension: IdentityDimensionKey,
  scoring: "direct" | "reverse",
  facet: string,
  displayOrder: number,
): IdentityQuestion => ({
  id,
  code,
  text,
  dimension,
  scoring,
  facet,
  displayOrder,
});

export const IDENTITY_PROFILE_QUESTIONS: IdentityQuestion[] = [
  question(1, "SC01", "I have a clear sense of the kind of person I am.", "self_clarity", "direct", "Self-Definition", 1),
  question(7, "AU01", "The way I behave around most people feels consistent with who I am privately.", "authenticity", "direct", "Self-Expression", 2),
  question(13, "VA01", "My important decisions usually reflect what genuinely matters to me.", "values_alignment", "direct", "Decision Alignment", 3),
  question(19, "SA01", "I naturally adjust the way I communicate depending on who I am talking to.", "social_adaptation", "direct", "Communication Adaptation", 4),
  question(25, "EI01", "Other people's expectations can strongly influence the choices I make.", "external_influence", "direct", "Expectation Influence", 5),
  question(31, "IS01", "Even when my environment changes, I retain a fairly stable sense of who I am.", "identity_stability", "direct", "Self-Continuity", 6),
  question(8, "AU02", "I sometimes act like a version of myself that does not feel genuinely like me.", "authenticity", "reverse", "Persona Gap", 7),
  question(32, "IS02", "My sense of who I am can change significantly depending on the people around me.", "identity_stability", "reverse", "Context Dependence", 8),
  question(2, "SC02", "I sometimes struggle to tell what I genuinely want from what I think I should want.", "self_clarity", "reverse", "Personal Wants", 9),
  question(26, "EI02", "I can maintain my own view of myself even when other people see me very differently.", "external_influence", "reverse", "Internal Grounding", 10),
  question(14, "VA02", "I sometimes make major choices mainly because they are expected of me rather than because I truly want them.", "values_alignment", "reverse", "Expectation Pressure", 11),
  question(20, "SA02", "I tend to behave almost exactly the same way regardless of the social setting.", "social_adaptation", "reverse", "Context Sensitivity", 12),
  question(15, "VA03", "I am willing to give up an attractive opportunity if it strongly conflicts with my principles.", "values_alignment", "direct", "Principle Commitment", 13),
  question(3, "SC03", "I can usually explain why certain things matter deeply to me.", "self_clarity", "direct", "Self-Understanding", 14),
  question(21, "SA03", "Different groups of people tend to see noticeably different sides of my personality.", "social_adaptation", "direct", "Contextual Expression", 15),
  question(9, "AU03", "I can usually express my real opinions without feeling that I need to become someone else.", "authenticity", "direct", "Honest Expression", 16),
  question(33, "IS03", "Although I continue to grow and change, there is a recognizable core in me that remains consistent.", "identity_stability", "direct", "Core Continuity", 17),
  question(27, "EI03", "I sometimes question my choices mainly because other people do not approve of them.", "external_influence", "direct", "Approval Sensitivity", 18),
  question(10, "AU04", "I often hide important parts of myself because I worry about how they will be received.", "authenticity", "reverse", "Self-Suppression", 19),
  question(22, "SA04", "I rarely change how I present myself to match the expectations of a situation.", "social_adaptation", "reverse", "Presentation Flexibility", 20),
  question(4, "SC04", "My understanding of who I am often feels unclear or difficult to define.", "self_clarity", "reverse", "Identity Clarity", 21),
  question(16, "VA04", "I sometimes compromise things that matter to me just to avoid disappointing other people.", "values_alignment", "reverse", "Values Compromise", 22),
  question(28, "EI04", "Comparing myself with other people rarely changes how I feel about my own worth or direction.", "external_influence", "reverse", "Comparison Independence", 23),
  question(34, "IS04", "I sometimes feel like such different versions of myself in different situations that I am unsure which one is really me.", "identity_stability", "reverse", "Identity Fragmentation", 24),
  question(5, "SC05", "I generally know which situations bring out the best and worst in me.", "self_clarity", "direct", "Pattern Awareness", 25),
  question(11, "AU05", "Even when I adapt to a situation, I still feel like I am being myself.", "authenticity", "direct", "Adaptive Authenticity", 26),
  question(17, "VA05", "The way I spend my time generally reflects the priorities I say are important to me.", "values_alignment", "direct", "Behavioral Alignment", 27),
  question(23, "SA05", "I can quickly sense the social atmosphere and adjust how I interact when needed.", "social_adaptation", "direct", "Social Calibration", 28),
  question(29, "EI05", "How people respond to me can significantly affect how I evaluate myself.", "external_influence", "direct", "Social Validation", 29),
  question(35, "IS05", "Major changes in my life may affect me, but they do not usually erase my underlying sense of self.", "identity_stability", "direct", "Change Stability", 30),
  question(18, "VA06", "There is often a noticeable gap between what I say matters to me and how I actually live.", "values_alignment", "reverse", "Values-Behavior Gap", 31),
  question(12, "AU06", "There are situations where fitting in matters so much that I behave in ways that feel unlike me.", "authenticity", "reverse", "Conformity Gap", 32),
  question(24, "SA06", "Moving between different social roles or environments usually does not change how I express myself.", "social_adaptation", "reverse", "Role Adaptation", 33),
  question(30, "EI06", "Even when people close to me disagree with my direction, I can usually separate their expectations from what I want for myself.", "external_influence", "reverse", "Expectation Independence", 34),
  question(6, "SC06", "I often need other people's opinions before I can make sense of how I feel about myself.", "self_clarity", "reverse", "Internal Reference", 35),
  question(36, "IS06", "My understanding of myself often shifts so much that it becomes difficult to know what genuinely represents me.", "identity_stability", "reverse", "Self-Concept Instability", 36),
].sort((a, b) => a.displayOrder - b.displayOrder);
