import type { RelationshipDimensionKey, RelationshipQuestion } from "./types";

export const PRIMARY_RELATIONSHIP_DIMENSIONS: RelationshipDimensionKey[] = [
  "emotional_closeness",
  "communication_openness",
  "trust_orientation",
  "relational_independence",
  "care_expression",
  "relationship_security",
];

export const CONFLICT_RELATIONSHIP_DIMENSIONS: RelationshipDimensionKey[] = [
  "conflict_direct",
  "conflict_avoidance",
  "conflict_accommodation",
  "conflict_escalation",
];

export const RELATIONSHIP_DIMENSIONS: Record<
  RelationshipDimensionKey,
  { label: string; shortLabel: string; description: string; color: string; soft: string }
> = {
  emotional_closeness: {
    label: "Emotional Closeness",
    shortLabel: "Closeness",
    description: "Comfort with vulnerability, emotional depth, and being supported by trusted people.",
    color: "#db2777",
    soft: "#fce7f3",
  },
  communication_openness: {
    label: "Communication Openness",
    shortLabel: "Communication",
    description: "Willingness to express needs, clarify meaning, and have important conversations.",
    color: "#2563eb",
    soft: "#dbeafe",
  },
  trust_orientation: {
    label: "Trust Orientation",
    shortLabel: "Trust",
    description: "How readily you allow earned trust and emotional reliability to develop.",
    color: "#0f766e",
    soft: "#ccfbf1",
  },
  relational_independence: {
    label: "Relational Independence",
    shortLabel: "Independence",
    description: "Ability to stay connected while keeping your own interests, direction, and boundaries.",
    color: "#7c3aed",
    soft: "#ede9fe",
  },
  care_expression: {
    label: "Care Expression",
    shortLabel: "Care",
    description: "How visibly you communicate care, appreciation, and support to people who matter.",
    color: "#f97316",
    soft: "#ffedd5",
  },
  relationship_security: {
    label: "Relationship Security",
    shortLabel: "Security",
    description: "How stable important relationships feel during distance, uncertainty, or minor disruption.",
    color: "#0284c7",
    soft: "#e0f2fe",
  },
  conflict_direct: {
    label: "Direct Conflict Engagement",
    shortLabel: "Direct",
    description: "Tendency to address disagreements directly instead of leaving them unspoken.",
    color: "#16a34a",
    soft: "#dcfce7",
  },
  conflict_avoidance: {
    label: "Conflict Avoidance",
    shortLabel: "Avoidance",
    description: "Tendency to postpone, withdraw from, or avoid tense conversations.",
    color: "#64748b",
    soft: "#f1f5f9",
  },
  conflict_accommodation: {
    label: "Conflict Accommodation",
    shortLabel: "Accommodation",
    description: "Tendency to concede, soften, or prioritize harmony during disagreement.",
    color: "#a855f7",
    soft: "#f3e8ff",
  },
  conflict_escalation: {
    label: "Conflict Escalation",
    shortLabel: "Escalation",
    description: "Tendency for conflict intensity to rise when emotionally activated.",
    color: "#dc2626",
    soft: "#fee2e2",
  },
};

const question = (
  id: number,
  code: string,
  text: string,
  dimension: RelationshipDimensionKey,
  scoring: "direct" | "reverse",
  facet: string,
  displayOrder: number,
): RelationshipQuestion => ({
  id,
  code,
  text,
  dimension,
  scoring,
  facet,
  displayOrder,
});

export const RELATIONSHIP_STYLE_QUESTIONS: RelationshipQuestion[] = [
  question(1, "EC01", "I feel comfortable letting people I trust see my vulnerable side.", "emotional_closeness", "direct", "Vulnerability", 1),
  question(7, "CO01", "When something matters to me in a relationship, I can usually explain it clearly.", "communication_openness", "direct", "Clear Expression", 2),
  question(13, "TO01", "When someone has consistently treated me well, I can usually allow myself to trust them.", "trust_orientation", "direct", "Earned Trust", 3),
  question(19, "RI01", "I can be deeply connected to someone while still maintaining my own interests and direction.", "relational_independence", "direct", "Individuality", 4),
  question(25, "CE01", "I make an effort to show people I care about that they matter to me.", "care_expression", "direct", "Visible Care", 5),
  question(31, "RS01", "A temporary change in someone's mood does not usually make me question the entire relationship.", "relationship_security", "direct", "Emotional Stability", 6),
  question(37, "CD01", "When an important disagreement arises, I prefer to address it rather than pretend nothing happened.", "conflict_direct", "direct", "Issue Engagement", 7),
  question(40, "CA01", "I sometimes avoid bringing up a problem because I would rather not deal with the tension it could create.", "conflict_avoidance", "direct", "Tension Avoidance", 8),
  question(43, "CC01", "During disagreements, I sometimes give up what I want because preserving the relationship feels more important.", "conflict_accommodation", "direct", "Harmony Priority", 9),
  question(46, "CX01", "When I feel strongly misunderstood during an argument, I can become more forceful than I intended.", "conflict_escalation", "direct", "Intensity", 10),
  question(8, "CO02", "I sometimes expect people close to me to understand what I need without me saying it directly.", "communication_openness", "reverse", "Unspoken Expectations", 11),
  question(32, "RS02", "When someone important becomes less responsive, I quickly start wondering whether something is wrong between us.", "relationship_security", "reverse", "Distance Sensitivity", 12),
  question(2, "EC02", "Even with people close to me, I tend to keep my deeper feelings to myself.", "emotional_closeness", "reverse", "Emotional Privacy", 13),
  question(20, "RI02", "When someone becomes very important to me, my own priorities can easily become secondary to theirs.", "relational_independence", "reverse", "Priority Merging", 14),
  question(14, "TO02", "Even when someone has given me little reason to doubt them, part of me still expects them to let me down.", "trust_orientation", "reverse", "Anticipated Disappointment", 15),
  question(26, "CE02", "People close to me may not always realize how much I care because I rarely show it directly.", "care_expression", "reverse", "Reserved Expression", 16),
  question(38, "CD02", "If someone's behavior is affecting our relationship, I am willing to discuss it directly with them.", "conflict_direct", "direct", "Direct Communication", 17),
  question(44, "CC02", "I am willing to let the other person have their way when I believe continuing the disagreement is not worth it.", "conflict_accommodation", "direct", "Concession", 18),
  question(41, "CA02", "When a disagreement becomes uncomfortable, my first instinct is often to withdraw from the conversation.", "conflict_avoidance", "direct", "Withdrawal", 19),
  question(47, "CX02", "During heated disagreements, I sometimes react first and think more carefully about what I said afterward.", "conflict_escalation", "direct", "Reactivity", 20),
  question(15, "TO03", "I can rely on people who have repeatedly shown that they are dependable.", "trust_orientation", "direct", "Reliance", 21),
  question(3, "EC03", "Meaningful relationships feel stronger to me when we can talk openly about personal feelings and experiences.", "emotional_closeness", "direct", "Emotional Depth", 22),
  question(27, "CE03", "When someone important to me is struggling, I usually look for a meaningful way to support them.", "care_expression", "direct", "Support", 23),
  question(9, "CO03", "I am willing to have an uncomfortable conversation when I believe it is important for the relationship.", "communication_openness", "direct", "Difficult Conversations", 24),
  question(33, "RS03", "I can usually believe that a strong relationship remains meaningful even when we are temporarily less connected.", "relationship_security", "direct", "Bond Continuity", 25),
  question(21, "RI03", "I am comfortable having some interests, friendships, or activities that are separate from the people closest to me.", "relational_independence", "direct", "Personal Space", 26),
  question(39, "CD03", "I prefer resolving important misunderstandings through conversation rather than leaving them unspoken.", "conflict_direct", "direct", "Resolution Orientation", 27),
  question(42, "CA03", "I may leave an issue unresolved for a long time if discussing it feels too uncomfortable.", "conflict_avoidance", "direct", "Conflict Delay", 28),
  question(48, "CX03", "The more strongly someone pushes against my position during a conflict, the more strongly I tend to push back.", "conflict_escalation", "direct", "Counter-Escalation", 29),
  question(45, "CC03", "I sometimes soften or withhold my own preference to keep a disagreement from becoming bigger.", "conflict_accommodation", "direct", "Preference Suppression", 30),
  question(22, "RI04", "I sometimes feel that being close to someone means we should do most important things together.", "relational_independence", "reverse", "Togetherness Dependence", 31),
  question(10, "CO04", "I often keep concerns to myself until they become difficult to ignore.", "communication_openness", "reverse", "Concern Suppression", 32),
  question(16, "TO04", "I tend to stay emotionally cautious even after someone has proven trustworthy over time.", "trust_orientation", "reverse", "Persistent Guardedness", 33),
  question(34, "RS04", "Small signs of distance can make me uncertain about how someone really feels about me.", "relationship_security", "reverse", "Relational Uncertainty", 34),
  question(4, "EC04", "I often feel uncomfortable when someone tries to become emotionally close to me too quickly.", "emotional_closeness", "reverse", "Closeness Comfort", 35),
  question(28, "CE04", "Even when I appreciate someone deeply, I can find it difficult to communicate that appreciation.", "care_expression", "reverse", "Appreciation Expression", 36),
  question(29, "CE05", "I pay attention to what makes the people I care about feel supported and valued.", "care_expression", "direct", "Responsive Care", 37),
  question(17, "TO05", "When a trustworthy person makes a small mistake, I can usually see it as a mistake rather than evidence that they cannot be trusted.", "trust_orientation", "direct", "Trust Resilience", 38),
  question(23, "RI05", "I can disagree with someone I care about without feeling that I have to abandon my own position.", "relational_independence", "direct", "Independent Position", 39),
  question(5, "EC05", "When I am struggling, I can usually allow someone I trust to support me emotionally.", "emotional_closeness", "direct", "Receiving Support", 40),
  question(11, "CO05", "If I am unsure what someone means, I would rather ask than make assumptions.", "communication_openness", "direct", "Clarification", 41),
  question(35, "RS05", "I generally feel secure about where I stand with people who have consistently shown that they care about me.", "relationship_security", "direct", "Relational Confidence", 42),
  question(36, "RS06", "I often need signs of reassurance before I can feel confident that an important relationship is okay.", "relationship_security", "reverse", "Reassurance Need", 43),
  question(6, "EC06", "I prefer handling difficult emotions on my own rather than letting people close to me see them.", "emotional_closeness", "reverse", "Emotional Self-Containment", 44),
  question(12, "CO06", "There are times when I say that everything is fine even though something is clearly bothering me.", "communication_openness", "reverse", "Emotional Withholding", 45),
  question(30, "CE06", "I tend to assume people close to me already know I care, so I do not always express it.", "care_expression", "reverse", "Assumed Understanding", 46),
  question(18, "TO06", "Once I start wondering whether someone can be trusted, it is very difficult for me to stop questioning them.", "trust_orientation", "reverse", "Trust Doubt", 47),
  question(24, "RI06", "I sometimes change important personal choices mainly to preserve closeness with someone.", "relational_independence", "reverse", "Relational Self-Sacrifice", 48),
].sort((a, b) => a.displayOrder - b.displayOrder);
